---
name: CI - Molecule
on:
  pull_request:
  push:
    branches:
      - main
      - stable-*
jobs:
  test:
    name: Molecule
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          python-version: '3.10'

      - name: Run molecule
        run: molecule test -s get_xml_tag
